import {DataType} from './DataInterface.types';
const initialData: DataType[] = [
  {
    key: "1",
    lastName: "Taylor",
    firstName: "Timothy",
    middleName: "James",
    suffix: null,
    dob: "12/13/1989",
    age: 35,
    address: "1234 August Ave",
    city: "St. Paul",
    state: "MN",
    recordValue: "",
  },
  {
    key: "2",
    lastName: "Taylor 1",
    firstName: "Timothy 1",
    middleName: null,
    suffix: null,
    dob: "12/13/1990",
    age: 35,
    address: "1234 August Ave",
    city: "St. Paul",
    state: "MN",
    recordValue: "",
  },
  {
    key: "3",
    lastName: "Taylor 2",
    firstName: "Timothy 2",
    middleName: "Drew",
    suffix: null,
    dob: "10/05/1987",
    age: 37,
    address: "1234 First Street",
    city: "St. Paul",
    state: "MN",
    recordValue: "",
  },
  {
    key: "4",
    lastName: "Taylor 3",
    firstName: "Timothy 3",
    middleName: "Drew",
    suffix: null,
    dob: "10/05/1987",
    age: 37,
    address: "1234 First Street",
    city: "St. Paul",
    state: "MN",
    recordValue: "",
  },
];

export default initialData;